### ISSUE TITLE
[BUG] Multiple dead links leading to 404s

### ISSUE THREAD

**Issue by ThugOG** [tangle-network/docs#72]
I have encountered several dead links and pages that lead to 404 errors on the Tangle documentation site. This issue affects the usability of the documentation and may hinder users from accessing important information.
Affected Links:
- [x] Introduction Page - Leads to a 404 error. Embedded link on -> [https://docs.tangle.tools/operators/validator/validator-rewards]
- [x] Account Management Page - Leads to a 404 error. Embedded link on -> [https://docs.tangle.tools/operators/validator/introduction]

The links should direct users to the appropriate documentation pages without leading to 404 errors.

You can check the video for better clarification here - https://streamable.com/z7fv1t

**Comment by yurixander** [comment]
@ThugOG Thank you for reporting! Will be fixed briefly.
